version: "3.8"

services:
  server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - default
    ports:
    - "${SERVER_PORT}:${SERVER_PORT}"
    - 6060:6060
    - 8080:8080
    volumes:
      - "./certs:/etc/ca-certificates/github.com/Shabashkin93/warning_tracker/"
      - "./logs:/logs/"
