version: "3.8"

services:
  cache:
    image: redis:alpine
    command: redis-server
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes: 
      - cache:/data
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    env_file: .env
    networks:
      - default
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_BACKUP_TIME=${REDIS_BACKUP_TIME}

  server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - cache
    networks:
      - default
    ports:
    - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - "./logs:/logs/"
    environment:
      - REDIS_ADDRESS=cache

volumes:
  redis:
  redis-config:
  cache:
