{
 "title": "Warnings",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "warnings",
   "type": "status-history",
   "gridPos": { "h": 19, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT created_at, count, branch AS branch, commit AS commit FROM \"warning_tracker\".\"warning\" WHERE branch != 'develop' LIMIT 500"
    },
    {
     "rawSql": "SELECT created_at, count AS \"develop count\", commit AS \"dev commit\"  FROM \"warning_tracker\".\"warning\" WHERE branch = 'develop' LIMIT 500"
    }
   ]
  },
  {
   "title": "Not Develop Graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT created_at, count FROM \"warning_tracker\".\"warning\" WHERE branch != 'develop' LIMIT 500"
    }
   ]
  },
  {
   "title": "Develop Graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT created_at, count FROM \"warning_tracker\".\"warning\" WHERE branch = 'develop' LIMIT 500"
    }
   ]
  }
 ]
}