version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: ${PROJECT_NAME}-prometheus
    env_file: .env
    restart: no
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - ${PROMETHEUS_PORT}:9090

  grafana:
    image: grafana/grafana-enterprise
    container_name: ${PROJECT_NAME}-grafana
    env_file: .env
    restart: always
    ports:
      - ${GRAFANA_PORT}:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
volumes:
  grafana_data: {}
